name       : notes
version    : 1.0.0
release    : 1
source     :
    - https://github.com/nuttyartist/notes/archive/v1.0.0.tar.gz : 53ab61be719a4aab37af15e9e9db1268f00448b3c75b2e155d716df76e6965b7
license    :
    - MPL-2.0
component  : office.notes
summary    : Note-taking application, write down your thoughts.
description: Note taking application, write down your thoughts. Notes is a tool for the things you need to write down off your brain. It is your place of expressing yourself. Notes is an open source and cross-platform project, and you're welcome to be part of it and contribute. We hope you will love it as much as we do.
builddeps    :
    - pkgconfig(Qt5Core)
    - pkgconfig(sqlite3)
rundeps    :
    - qt5-base
setup      : |
    %qmake src/Notes.pro
build      : |
    %make
install    : |
    install -Dm00755 notes $installdir/usr/bin/notes
    install -Dm00644 src/images/notes_icon.ico $installdir/usr/share/pixmaps/notes_icon.ico
    install -Dm00644 $pkgfiles/notes.desktop $installdir/usr/share/applications/notes.desktop
