name       : notes
version    : 2.1.0
release    : 4
source     :
    - git|https://github.com/nuttyartist/notes.git : v2.1.0
license    :
    - MPL-2.0
component  : office.notes
summary    : Note-taking application, write down your thoughts.
description : |
    Note taking application, write down your thoughts. Notes is a tool for the things you need to write down off your brain. It is your place of expressing yourself.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(x11-xcb)
setup      : |
    %cmake_ninja  -DCMAKE_BUILD_TYPE=Release -DUPDATE_CHECKER=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
